# Generated by Django 4.0.4 on 2022-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/news')),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
    ]
